### ISSUE TITLE
latest release version is unclear

### ISSUE THREAD

**Issue by jku** [actions/checkout#1497]
* Marketplace claims latest version is v4.1.0: https://github.com/marketplace/actions/checkout, dependabot also suggests upgrading to 4.1.0
* Project releases show v4.0.0 as latest release  https://github.com/actions/checkout

**Comment by cpanato** [comment]
have the same concern

**Comment by ArjunDandagi** [comment]
looks like it is fixed . i see `v4.1.0` as the latest version

**Comment by JAGulin** [comment]
Maybe the 4.0 release should be removed? They forgot to update the v4.0 description so that still says v3.
https://github.com/marketplace/actions/checkout?version=v4.0.0
If possible, there should be a test-case to check that it's updated before release.
https://github.com/actions/checkout/commit/72f2cec99f417b1a1c5e2e88945068983b7965f9
Also, the changelog seems to be updated routinely, so perhaps link to that under "What's new".
https://github.com/actions/checkout/blob/main/CHANGELOG.md

**Comment by cory-miller** [comment]
Thanks for calling this out. The marketplace page for v4.0.0 is updated (we generally keep previous tags for releases around as not everyone references this action using `actions/checkout@v4` for example). I've also updated the what's new section to link back into the release notes and updated the marketplace page so it shows this.
