### ISSUE TITLE
is checkout@v2 behavior changed from v1

### ISSUE THREAD

**Issue by bitsf** [actions/checkout#167]
Because of issue #23 in v1, I'm trying to upgrade to v2, but find the checkout behavior is changed, in v1 when we set the path, the following steps will auto change to use that sub path, but in v2 it will stay to the origin root folder.
Is it a break change by design or a bug ?
And do I have to add "cd ..." to each following many steps ? Or there's other way to set this root folder

**Comment by ericsciple** [comment]
@chrispat fyi this sounds like being able to set working directory would solve

**Comment by ericsciple** [comment]
@bitsf The change is [intentional](https://github.com/actions/checkout/blob/master/adrs/0153-checkout-v2.md#path).

If you are using the `run` step, then you can set the working directory:
```yaml
- run: pwd
  working-directory: ./temp
```

**Comment by chrispat** [comment]
It is by design to do that so you could put multiple repos SxS and have a consistent knowledge of the working directory.  You can set the working directory on the run step so you don't have to CD in your scripts https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun.
