### ISSUE TITLE
checkout@v2  aws s3 sync error code 255

### ISSUE THREAD

**Issue by jcharnley** [actions/checkout#440]
My pipeline has randomly stopped working, it worked yesterday and now gets back  error:

Run aws s3 sync ./ s3://d3plotviewer/d3plotviewer-source --exclude='node_modules/*' --exclude='.git/*'
  aws s3 sync ./ s3://d3plotviewer/d3plotviewer-source --exclude='node_modules/*' --exclude='.git/*'
  shell: /usr/bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***

<botocore.awsrequest.AWSRequest object at 0x7f76be627710>
Error: Process completed with exit code 255.

Pipeline is 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test Script
        run: npm install && npm run test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload Dir to S3 -source
        run: aws s3 sync ./ s3://d3plotviewer/d3plotviewer-source --exclude='node_modules/*' --exclude='.git/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

Anything any changed recently? or anyone else having issues>?

**Comment by jcharnley** [comment]
fyi, the command works locally and has been working for 5 months in the pipeline without any issues until today. No changes since it was setup....

**Comment by nabeen** [comment]
@jcharnley 
I'm having the same problem. But I think this is not a `checkout@v2` problem, caused by the change of `ubuntu-latest`. `ubuntu-latest` have changed from `Ubuntu 18.04` to `Ubuntu 20.04`.

- [Release Ubuntu 2004 \(20210208 update\) · actions/virtual\-environments](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210208.0)
- [Ubuntu\-latest workflows will use Ubuntu\-20\.04 · Issue \#1816 · actions/virtual\-environments](https://github.com/actions/virtual-environments/issues/1816)

Try using `ubuntu-18.04` as a first aid!

**Comment by jcharnley** [comment]
Thanks I saw that in a note somewhere, i'll give it a try

**Comment by jcharnley** [comment]
Brilliant ubuntu-18.04 works, thank u @nabeen :)

**Comment by hayd** [comment]
Has anyone come up with a solution on 20.04 ? This is very strange. (would be nice to understand the issue)

**Comment by hayd** [comment]
https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151

Setting `AWS_EC2_METADATA_DISABLED=true` fixed it for me.

**Comment by arvinep** [comment]
In case anyone else had the same issue, I handled the exit 2 skipping files warning here: https://github.com/aws/aws-cli/issues/5262#issuecomment-3166831240
