### ISSUE TITLE
workflows that relied on a tag for versioning no longer work

### ISSUE THREAD

**Issue by lamont** [actions/checkout#85]
Yesterday I had a anothrNick/github-tag-action based workflow which incremented the last tag on master upon PR-merge. (I use that tag during the terraform apply to tag AWS resources with whatever version of my repo) This morning's changes for V2 appears to always checkout with --no-tags, which breaks that workflow. From the V2 PR changes, I don't see how I can use the V2 actions/checkout and retain the last tag. In the meantime I'll pin actions/checkout to yesterday's version so my workflows work again

**Comment by lightswitch05** [comment]
I too am using tags, pulling them in manually with `git fetch --tags`

**Comment by ericsciple** [comment]
@lamont rather than yesterdays version, consider binding to `actions/checkout@v1` (basically yesterdays version, but will get future updates for the v1 channel)

**Comment by lamont** [comment]
Thank you @ericsciple, I'd bound to v1.2.0 but will change to v1 as per your suggestion.

**Comment by ericsciple** [comment]
@lamont regarding the tags... we made perf improvements for the v2 version so that only a single commit is fetched. However another advantage of the v2 version is that it makes it easier to script authenticated git commands (auth token persisted in the git config). So as @lightswitch05 mentioned you can `git fetch --tags` to get all of the tags. hth and sorry for the inconvenience.

**Comment by lamont** [comment]
Thanks for the followup (and work!).
